---
# Install EPE
- name: Install EPEL | CentOS-Rocky
  package:
    name: epel-release
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "RedHat"

- name: Install EPEL | RedHat 8+
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version >= "8"
  block:

    - name: Import EPEL GPG key | RedHat 8+
      rpm_key:
        key: "http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        state: present

    - name: Install EPEL | RedHat 8+
      package:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present


- name: Install EPEL | RedHat 7
  yum_repository:
    name: epel
    description: EPEL
    baseurl: "https://dl.fedoraproject.org/pub/archive/epel/7/x86_64/"
    gpgkey: "http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    enabled: true
  when:
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"


# this might change with other OS, will verify when I do full testing
- name: Install Addtional Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - collectd  # this is required if you are using logs
