---
- name: Preflight
  include_tasks: preflight.yml

# Check to see if installed?

- name: Install cloudwatch-agent
  include_tasks: install-cwagent.yml

- name: Configure cloudwatch-agent
  include_tasks: configure-cwagent.yml


# - name: Check if rtpengine is installed
#   command: "which {{ rtpengine_install_dir }}/usr/bin/rtpengine"
#   register: rtpengine_exists
#   failed_when: false
#   ignore_errors: true
#   changed_when: false
